### PR TITLE
CNV-29315: kubevirt-csi unable to unpublish volumes in the event a VM is unexpectedly destroyed

### PR DESCRIPTION
**Pull request by awels**
**What this PR does / why we need it**:
https://github.com/kubevirt/csi-driver has some new PRs, in particular a fix to controller unpublish that we would like to use. As well as fsGroup support. Also update to golang 1.19.7 and update some libraries to the latest version.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
/retitle [CNV-24818](https://issues.redhat.com/browse/CNV-24818): Add fsGroup support to kubevirt-csi-driver

**Comment by davidvossel** [comment]
fixes: #[CNV-24818](https://issues.redhat.com/browse/CNV-24818)

**Pull request merged**
